"""Initial migration - create provider_xpaths, flight_results, search_logs tables

Revision ID: c5592b1372f5
Revises: 
Create Date: 2026-03-31 23:46:38.890901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5592b1372f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('search_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('airline', sa.String(length=255), nullable=False),
    sa.Column('flight_number', sa.String(length=50), nullable=True),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('destination', sa.String(length=10), nullable=False),
    sa.Column('departure_time', sa.String(length=50), nullable=False),
    sa.Column('arrival_time', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('stops', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('cabin_class', sa.String(length=50), nullable=False),
    sa.Column('booking_link', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flight_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flight_results_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_flight_results_search_id'), ['search_id'], unique=False)

    op.create_table('provider_xpaths',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('xpath', sa.Text(), nullable=True),
    sa.Column('css_selector', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_xpaths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_xpaths_field_name'), ['field_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_xpaths_provider_name'), ['provider_name'], unique=False)

    op.create_table('search_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('search_id', sa.String(length=36), nullable=False),
    sa.Column('request_params', sa.JSON(), nullable=False),
    sa.Column('providers_requested', sa.JSON(), nullable=False),
    sa.Column('total_results', sa.Integer(), nullable=False),
    sa.Column('total_errors', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_logs_search_id'), ['search_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_logs_search_id'))

    op.drop_table('search_logs')
    with op.batch_alter_table('provider_xpaths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_xpaths_provider_name'))
        batch_op.drop_index(batch_op.f('ix_provider_xpaths_field_name'))

    op.drop_table('provider_xpaths')
    with op.batch_alter_table('flight_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flight_results_search_id'))
        batch_op.drop_index(batch_op.f('ix_flight_results_provider'))

    op.drop_table('flight_results')
    # ### end Alembic commands ###
